name: hsma_cpd_project
description: 'A new Flutter project.'
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mockito: ^5.0.0

  cupertino_icons: ^1.0.6
  go_router: ^14.1.3
  provider: ^6.1.2
  fl_chart: ^0.68.0
  dart_jsonwebtoken: ^2.14.0

dev_dependencies:
  mocktail: ^1.0.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.webp
    - assets/rocket.png
    - assets/roulette.png
    - assets/roulette_ball.png
    - assets/coin_heads.png
    - assets/coin_tails.png
    - assets/cards/back.webp
    - assets/cards/clubs_1.png
    - assets/cards/clubs_10.png
    - assets/cards/clubs_11.png
    - assets/cards/clubs_12.png
    - assets/cards/clubs_13.png
    - assets/cards/clubs_2.png
    - assets/cards/clubs_3.png
    - assets/cards/clubs_4.png
    - assets/cards/clubs_5.png
    - assets/cards/clubs_6.png
    - assets/cards/clubs_7.png
    - assets/cards/clubs_8.png
    - assets/cards/clubs_9.png
    - assets/cards/diamonds_1.png
    - assets/cards/diamonds_10.png
    - assets/cards/diamonds_11.png
    - assets/cards/diamonds_12.png
    - assets/cards/diamonds_13.png
    - assets/cards/diamonds_2.png
    - assets/cards/diamonds_3.png
    - assets/cards/diamonds_4.png
    - assets/cards/diamonds_5.png
    - assets/cards/diamonds_6.png
    - assets/cards/diamonds_7.png
    - assets/cards/diamonds_8.png
    - assets/cards/diamonds_9.png
    - assets/cards/hearts_1.png
    - assets/cards/hearts_10.png
    - assets/cards/hearts_11.png
    - assets/cards/hearts_12.png
    - assets/cards/hearts_13.png
    - assets/cards/hearts_2.png
    - assets/cards/hearts_3.png
    - assets/cards/hearts_4.png
    - assets/cards/hearts_5.png
    - assets/cards/hearts_6.png
    - assets/cards/hearts_7.png
    - assets/cards/hearts_8.png
    - assets/cards/hearts_9.png
    - assets/cards/joker.png
    - assets/cards/spades_1.png
    - assets/cards/spades_10.png
    - assets/cards/spades_11.png
    - assets/cards/spades_12.png
    - assets/cards/spades_13.png
    - assets/cards/spades_2.png
    - assets/cards/spades_3.png
    - assets/cards/spades_4.png
    - assets/cards/spades_5.png
    - assets/cards/spades_6.png
    - assets/cards/spades_7.png
    - assets/cards/spades_8.png
    - assets/cards/spades_9.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
