import 'package:flutter/material.dart';
import 'package:hsma_cpd_project/logic/roulette_logic.dart' as roulette_logic;

class AppColors {
  static const Color primary = Colors.teal;
  static const Color primaryLight = Color(0xFF66CAC2);
  static const Color primaryDark = Color(0xFF00796B);
  static const Color accent = Color(0xFF26A69A);
  static const Color gray = Colors.grey;
}

const List<String> pokerDeckOfCards = [
  'clubs_1',
  'clubs_2',
  'clubs_3',
  'clubs_4',
  'clubs_5',
  'clubs_6',
  'clubs_7',
  'clubs_8',
  'clubs_9',
  'clubs_10',
  'clubs_11',
  'clubs_12',
  'clubs_13',
  'diamonds_1',
  'diamonds_2',
  'diamonds_3',
  'diamonds_4',
  'diamonds_5',
  'diamonds_6',
  'diamonds_7',
  'diamonds_8',
  'diamonds_9',
  'diamonds_10',
  'diamonds_11',
  'diamonds_12',
  'diamonds_13',
  'hearts_1',
  'hearts_2',
  'hearts_3',
  'hearts_4',
  'hearts_5',
  'hearts_6',
  'hearts_7',
  'hearts_8',
  'hearts_9',
  'hearts_10',
  'hearts_11',
  'hearts_12',
  'hearts_13',
  'spades_1',
  'spades_2',
  'spades_3',
  'spades_4',
  'spades_5',
  'spades_6',
  'spades_7',
  'spades_8',
  'spades_9',
  'spades_10',
  'spades_11',
  'spades_12',
  'spades_13',
  'joker'
];

const List<(int, roulette_logic.GuessType)> rouletteNumbers = [
  (0, roulette_logic.GuessType.green),
  (26, roulette_logic.GuessType.black),
  (3, roulette_logic.GuessType.red),
  (35, roulette_logic.GuessType.black),
  (12, roulette_logic.GuessType.red),
  (28, roulette_logic.GuessType.black),
  (7, roulette_logic.GuessType.red),
  (29, roulette_logic.GuessType.black),
  (18, roulette_logic.GuessType.red),
  (22, roulette_logic.GuessType.black),
  (9, roulette_logic.GuessType.red),
  (31, roulette_logic.GuessType.black),
  (14, roulette_logic.GuessType.red),
  (20, roulette_logic.GuessType.black),
  (1, roulette_logic.GuessType.red),
  (33, roulette_logic.GuessType.black),
  (16, roulette_logic.GuessType.red),
  (24, roulette_logic.GuessType.black),
  (5, roulette_logic.GuessType.red),
  (10, roulette_logic.GuessType.black),
  (23, roulette_logic.GuessType.red),
  (8, roulette_logic.GuessType.black),
  (30, roulette_logic.GuessType.red),
  (11, roulette_logic.GuessType.black),
  (36, roulette_logic.GuessType.red),
  (13, roulette_logic.GuessType.black),
  (27, roulette_logic.GuessType.red),
  (6, roulette_logic.GuessType.black),
  (34, roulette_logic.GuessType.red),
  (17, roulette_logic.GuessType.black),
  (25, roulette_logic.GuessType.red),
  (2, roulette_logic.GuessType.black),
  (21, roulette_logic.GuessType.red),
  (4, roulette_logic.GuessType.black),
  (19, roulette_logic.GuessType.red),
  (15, roulette_logic.GuessType.black),
  (32, roulette_logic.GuessType.red)
];
